export {default as TheAlert} from './TheAlert'
export {default as TheContent} from './TheContent'
export {default as TheButton} from './TheButton'
export {default as TheModal} from './TheModal'
export {default as TheTab} from './TheTab'
export {default as TopOrnamentLine} from './TopOrnamentLine'
export {default as BottomOrnamentLine} from './BottomOrnamentLine'
export {default as TheDeliveryTabs} from './tabs/TheDeliveryTabs'
